//! macOS Cocoa 原生平台驱动实现，基于 AppKit NSPasteboard、Vision 离线 OCR 与 CoreGraphics 提供剪贴板交互与按键模拟。
//!
//! @author Ateng
//! @since 2026-10-09

use crate::pal::anchor::{
    calculate_flip_fit_position, AnchorPoint, ScreenRect, DEFAULT_ANCHOR_MARGIN,
};
use crate::pal::{PalError, PlatformDriver};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::thread;
use std::time::Duration;

use objc2::rc::Retained;
use objc2::runtime::{AnyClass, AnyObject};
use objc2_app_kit::{
    NSPasteboard, NSPasteboardTypePNG, NSPasteboardTypeString, NSRunningApplication, NSWorkspace,
};
use objc2_foundation::{NSArray, NSData, NSString};

/// 密码管理器专有隐私排除标记列表
pub const MACOS_IGNORED_TYPES: &[&str] = &[
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
];

/// macOS 虚拟键码：ANSI 键盘 'V' 键码
const KEY_CODE_V: u16 = 9;

/// CoreGraphics 事件标记掩码：Command 键
const CG_EVENT_FLAG_COMMAND: u64 = 0x00100000;

/// CoreGraphics HID 级事件派发位置
const CG_HID_EVENT_TAP: u32 = 0;

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct CGPoint {
    pub x: f64,
    pub y: f64,
}

extern "C" {
    fn CGEventCreate(source: *mut std::ffi::c_void) -> *mut std::ffi::c_void;
    fn CGEventGetLocation(event: *mut std::ffi::c_void) -> CGPoint;
    fn CGEventCreateKeyboardEvent(
        source: *mut std::ffi::c_void,
        virtual_key: u16,
        key_down: bool,
    ) -> *mut std::ffi::c_void;
    fn CGEventSetFlags(event: *mut std::ffi::c_void, flags: u64);
    fn CGEventPost(tap: u32, event: *mut std::ffi::c_void);
    fn CFRelease(cf: *mut std::ffi::c_void);
    fn AXIsProcessTrusted() -> bool;
    fn CGMainDisplayID() -> u32;
    fn CGDisplayPixelsWide(display: u32) -> usize;
    fn CGDisplayPixelsHigh(display: u32) -> usize;
}

/// macOS Cocoa 原生平台驱动 (Cocoa Driver)
pub struct MacosPlatformDriver {
    is_monitoring: Arc<AtomicBool>,
    heartbeat_interval: Duration,
}

impl MacosPlatformDriver {
    /// 创建 macOS 原生平台驱动实例（默认 250ms 心跳轮询间隔）
    pub fn new() -> Self {
        Self {
            is_monitoring: Arc::new(AtomicBool::new(false)),
            heartbeat_interval: Duration::from_millis(250),
        }
    }

    /// 使用自定义轮询间隔创建实例（主要用于单测与能耗调优）
    pub fn with_heartbeat_interval(interval: Duration) -> Self {
        Self {
            is_monitoring: Arc::new(AtomicBool::new(false)),
            heartbeat_interval: interval,
        }
    }

    /// 检查类型名称切片中是否命中已知密码管理器隐私排除标记
    pub fn matches_ignored_type(types: &[String]) -> bool {
        types.iter().any(|t| {
            MACOS_IGNORED_TYPES.iter().any(|ignored| t == ignored)
        })
    }

    /// 检查当前进程是否具备系统辅助功能 (Accessibility) 按键注入权限
    pub fn is_accessibility_trusted() -> bool {
        unsafe { AXIsProcessTrusted() }
    }

    /// 获取 macOS 物理鼠标绝对坐标与当前主屏幕可视工作区
    pub fn get_pointer_and_screen() -> Result<(AnchorPoint, ScreenRect), PalError> {
        unsafe {
            let event = CGEventCreate(std::ptr::null_mut());
            if event.is_null() {
                return Err(PalError::InternalError("无法创建 CoreGraphics 事件探针".into()));
            }
            let loc = CGEventGetLocation(event);
            CFRelease(event);

            let main_display = CGMainDisplayID();
            let width = CGDisplayPixelsWide(main_display) as i32;
            let height = CGDisplayPixelsHigh(main_display) as i32;

            let anchor = AnchorPoint::Point {
                x: loc.x as i32,
                y: loc.y as i32,
            };

            let screen_rect = ScreenRect {
                left: 0,
                top: 0,
                right: if width > 0 { width } else { 1920 },
                bottom: if height > 0 { height } else { 1080 },
            };

            Ok((anchor, screen_rect))
        }
    }

    /// 计算主面板在 macOS 屏幕上的四向翻转贴靠坐标
    pub fn get_window_anchor_position(width: i32, height: i32) -> (i32, i32) {
        if let Ok((anchor, screen_rect)) = Self::get_pointer_and_screen() {
            calculate_flip_fit_position(&anchor, width, height, &screen_rect, DEFAULT_ANCHOR_MARGIN)
        } else {
            // 降级回退至屏幕常规坐标
            (100, 100)
        }
    }
}

impl Default for MacosPlatformDriver {
    fn default() -> Self {
        Self::new()
    }
}

impl PlatformDriver for MacosPlatformDriver {
    fn read_text(&self) -> Result<Option<String>, PalError> {
        let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
        let ns_string_opt = unsafe { pasteboard.stringForType(NSPasteboardTypeString) };
        Ok(ns_string_opt.map(|s| s.to_string()))
    }

    fn write_text(&self, text: &str) -> Result<(), PalError> {
        let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
        unsafe {
            let _ = pasteboard.clearContents();
            let ns_str = NSString::from_str(text);
            if !pasteboard.setString_forType(&ns_str, NSPasteboardTypeString) {
                return Err(PalError::ClipboardError("写入 macOS 剪贴板文本失败".into()));
            }
        }
        Ok(())
    }

    fn read_image(&self) -> Result<Option<Vec<u8>>, PalError> {
        let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
        let ns_data_opt = unsafe { pasteboard.dataForType(NSPasteboardTypePNG) };
        Ok(ns_data_opt.map(|data| data.as_bytes().to_vec()))
    }

    fn write_image(&self, data: &[u8]) -> Result<(), PalError> {
        let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
        unsafe {
            let _ = pasteboard.clearContents();
            let ns_data = NSData::with_bytes(data);
            if !pasteboard.setData_forType(Some(&ns_data), NSPasteboardTypePNG) {
                return Err(PalError::ClipboardError("写入 macOS 剪贴板图片失败".into()));
            }
        }
        Ok(())
    }

    fn send_paste(&self) -> Result<(), PalError> {
        // 1. 预检辅助功能权限，未授权时触发 Accessibility Fallback
        if !Self::is_accessibility_trusted() {
            return Err(PalError::InputSimulationError(
                "未获得 macOS 辅助功能 (Accessibility) 权限，无法模拟 Cmd+V 按键".into(),
            ));
        }

        // 2. 使用 CoreGraphics 注入 Cmd+V 组合按键
        unsafe {
            let key_down = CGEventCreateKeyboardEvent(std::ptr::null_mut(), KEY_CODE_V, true);
            if key_down.is_null() {
                return Err(PalError::InputSimulationError("创建 Cmd+V 按下事件失败".into()));
            }
            CGEventSetFlags(key_down, CG_EVENT_FLAG_COMMAND);
            CGEventPost(CG_HID_EVENT_TAP, key_down);
            CFRelease(key_down);

            thread::sleep(Duration::from_millis(15));

            let key_up = CGEventCreateKeyboardEvent(std::ptr::null_mut(), KEY_CODE_V, false);
            if key_up.is_null() {
                return Err(PalError::InputSimulationError("创建 Cmd+V 释放事件失败".into()));
            }
            CGEventSetFlags(key_up, CG_EVENT_FLAG_COMMAND);
            CGEventPost(CG_HID_EVENT_TAP, key_up);
            CFRelease(key_up);
        }

        Ok(())
    }

    fn start_monitor(&self, callback: Arc<dyn Fn() + Send + Sync>) -> Result<(), PalError> {
        // 1. 防止重复启动监听循环
        if self.is_monitoring.swap(true, Ordering::SeqCst) {
            return Ok(());
        }

        let is_monitoring = self.is_monitoring.clone();
        let interval = self.heartbeat_interval;

        // 2. 启动 250ms 自适应心跳轮询线程 (Heartbeat Poller)
        thread::spawn(move || {
            let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
            let mut last_change_count = unsafe { pasteboard.changeCount() };
            let mut last_tick = std::time::Instant::now();

            while is_monitoring.load(Ordering::Relaxed) {
                thread::sleep(interval);

                // 能耗保护：检测系统挂起/休眠唤醒（时间跨度远大于轮询周期表示刚从休眠中唤醒）
                let now = std::time::Instant::now();
                let elapsed = now.duration_since(last_tick);
                last_tick = now;

                if elapsed > interval * 4 {
                    // 系统刚从休眠中恢复，重置并同步最新 change_count，避免能耗浪费与抖动
                    last_change_count = unsafe { pasteboard.changeCount() };
                    continue;
                }

                let current_change_count = unsafe { pasteboard.changeCount() };
                if current_change_count != last_change_count {
                    last_change_count = current_change_count;
                    callback();
                }
            }
        });

        Ok(())
    }

    fn is_clipboard_ignored(&self) -> Result<bool, PalError> {
        let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
        let types_opt: Option<Retained<NSArray<_>>> = unsafe { pasteboard.types() };

        if let Some(types) = types_opt {
            let type_names: Vec<String> = types.iter().map(|t| t.to_string()).collect();
            return Ok(Self::matches_ignored_type(&type_names));
        }

        Ok(false)
    }

    fn get_clipboard_source_process(&self) -> Result<Option<String>, PalError> {
        let workspace = unsafe { NSWorkspace::sharedWorkspace() };
        let app_opt: Option<Retained<NSRunningApplication>> =
            unsafe { workspace.frontmostApplication() };

        if let Some(app) = app_opt {
            if let Some(name) = unsafe { app.localizedName() } {
                return Ok(Some(name.to_string()));
            }
            if let Some(bundle_id) = unsafe { app.bundleIdentifier() } {
                return Ok(Some(bundle_id.to_string()));
            }
        }

        Ok(None)
    }

    fn ocr_image(&self, data: &[u8]) -> Result<String, PalError> {
        if data.is_empty() {
            return Ok(String::new());
        }

        // 对接 Apple Vision 原生离线 OCR 框架 (VNRecognizeTextRequest)
        // 在 macOS 10.15+ 环境下原生内置，0MB 外部模型开销
        unsafe {
            let ns_data = NSData::with_bytes(data);

            let handler_class = match AnyClass::get("VNImageRequestHandler") {
                Some(cls) => cls,
                None => return Ok(String::new()),
            };

            let request_class = match AnyClass::get("VNRecognizeTextRequest") {
                Some(cls) => cls,
                None => return Ok(String::new()),
            };

            // 1. 初始化 VNRecognizeTextRequest
            let request: *mut AnyObject = objc2::msg_send![request_class, new];
            if request.is_null() {
                return Ok(String::new());
            }

            // 2. 初始化 VNImageRequestHandler
            let dict_cls = match AnyClass::get("NSDictionary") {
                Some(cls) => cls,
                None => {
                    let () = objc2::msg_send![request, release];
                    return Ok(String::new());
                }
            };
            let options: *mut AnyObject = objc2::msg_send![dict_cls, dictionary];
            let handler: *mut AnyObject = objc2::msg_send![handler_class, alloc];
            let handler: *mut AnyObject = objc2::msg_send![handler, initWithData: &*ns_data, options: options];
            if handler.is_null() {
                let () = objc2::msg_send![request, release];
                return Ok(String::new());
            }

            // 3. 执行文字识别请求
            let retained_req = match Retained::retain(request) {
                Some(r) => r,
                None => {
                    let () = objc2::msg_send![handler, release];
                    let () = objc2::msg_send![request, release];
                    return Ok(String::new());
                }
            };
            let requests = NSArray::from_vec(vec![retained_req]);
            let mut error: *mut AnyObject = std::ptr::null_mut();
            let success: bool = objc2::msg_send![handler, performRequests: &*requests, error: &mut error];

            let mut extracted_text = String::new();
            if success {
                let results: *mut AnyObject = objc2::msg_send![request, results];
                if !results.is_null() {
                    let count: usize = objc2::msg_send![results, count];
                    for i in 0..count {
                        let observation: *mut AnyObject = objc2::msg_send![results, objectAtIndex: i];
                        let candidates: *mut AnyObject = objc2::msg_send![observation, topCandidates: 1usize];
                        if !candidates.is_null() {
                            let cand_count: usize = objc2::msg_send![candidates, count];
                            if cand_count > 0 {
                                let top: *mut AnyObject = objc2::msg_send![candidates, objectAtIndex: 0usize];
                                let cand_str: *mut AnyObject = objc2::msg_send![top, string];
                                if !cand_str.is_null() {
                                    let utf8_ptr: *const std::ffi::c_char = objc2::msg_send![cand_str, UTF8String];
                                    if !utf8_ptr.is_null() {
                                        if let Ok(line) = std::ffi::CStr::from_ptr(utf8_ptr).to_str() {
                                            if !extracted_text.is_empty() {
                                                extracted_text.push('\n');
                                            }
                                            extracted_text.push_str(line);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            let () = objc2::msg_send![handler, release];
            let () = objc2::msg_send![request, release];

            Ok(extracted_text)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_matches_ignored_type_all_branches() {
        assert!(MacosPlatformDriver::matches_ignored_type(&[
            "org.nspasteboard.TransientType".to_string()
        ]));
        assert!(MacosPlatformDriver::matches_ignored_type(&[
            "org.nspasteboard.ConcealedType".to_string()
        ]));
        assert!(MacosPlatformDriver::matches_ignored_type(&[
            "org.nspasteboard.AutoGeneratedType".to_string()
        ]));
        assert!(MacosPlatformDriver::matches_ignored_type(&[
            "com.agilebits.onepassword".to_string()
        ]));
        assert!(!MacosPlatformDriver::matches_ignored_type(&[
            "public.utf8-plain-text".to_string(),
            "public.png".to_string(),
        ]));
    }

    #[test]
    fn test_default_heartbeat_interval() {
        let driver = MacosPlatformDriver::new();
        assert_eq!(driver.heartbeat_interval, Duration::from_millis(250));

        let driver_custom = MacosPlatformDriver::with_heartbeat_interval(Duration::from_millis(100));
        assert_eq!(driver_custom.heartbeat_interval, Duration::from_millis(100));
    }

    #[test]
    fn test_ocr_image_empty_data_returns_empty_string() {
        let driver = MacosPlatformDriver::new();
        assert_eq!(driver.ocr_image(&[]).unwrap(), "");
    }
}
