//! macOS Cocoa 原生平台驱动实现，基于 AppKit NSPasteboard 与 CoreGraphics 提供剪贴板交互与按键模拟。
//!
//! @author Ateng
//! @since 2026-10-09

use crate::pal::{PalError, PlatformDriver};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::thread;
use std::time::Duration;

use objc2::rc::Retained;
use objc2_app_kit::{
    NSPasteboard, NSPasteboardTypePNG, NSPasteboardTypeString, NSRunningApplication, NSWorkspace,
};
use objc2_foundation::{NSArray, NSData, NSString};

/// 密码管理器专有隐私排除标记列表
pub const MACOS_IGNORED_TYPES: &[&str] = &[
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
];

/// macOS 虚拟键码：ANSI 键盘 'V' 键码
const KEY_CODE_V: u16 = 9;

/// CoreGraphics 事件标记掩码：Command 键
const CG_EVENT_FLAG_COMMAND: u64 = 0x00100000;

/// CoreGraphics HID 级事件派发位置
const CG_HID_EVENT_TAP: u32 = 0;

extern "C" {
    fn CGEventCreateKeyboardEvent(
        source: *mut std::ffi::c_void,
        virtual_key: u16,
        key_down: bool,
    ) -> *mut std::ffi::c_void;
    fn CGEventSetFlags(event: *mut std::ffi::c_void, flags: u64);
    fn CGEventPost(tap: u32, event: *mut std::ffi::c_void);
    fn CFRelease(cf: *mut std::ffi::c_void);
    fn AXIsProcessTrusted() -> bool;
}

/// macOS Cocoa 原生平台驱动 (Cocoa Driver)
pub struct MacosPlatformDriver {
    is_monitoring: Arc<AtomicBool>,
    heartbeat_interval: Duration,
}

impl MacosPlatformDriver {
    /// 创建 macOS 原生平台驱动实例（默认 250ms 心跳轮询间隔）
    pub fn new() -> Self {
        Self {
            is_monitoring: Arc::new(AtomicBool::new(false)),
            heartbeat_interval: Duration::from_millis(250),
        }
    }

    /// 使用自定义轮询间隔创建实例（主要用于单测与能耗调优）
    pub fn with_heartbeat_interval(interval: Duration) -> Self {
        Self {
            is_monitoring: Arc::new(AtomicBool::new(false)),
            heartbeat_interval: interval,
        }
    }

    /// 检查类型名称切片中是否命中已知密码管理器隐私排除标记
    pub fn matches_ignored_type(types: &[String]) -> bool {
        types.iter().any(|t| {
            MACOS_IGNORED_TYPES.iter().any(|ignored| t == ignored)
        })
    }

    /// 检查当前进程是否具备系统辅助功能 (Accessibility) 按键注入权限
    pub fn is_accessibility_trusted() -> bool {
        unsafe { AXIsProcessTrusted() }
    }
}

impl Default for MacosPlatformDriver {
    fn default() -> Self {
        Self::new()
    }
}

impl PlatformDriver for MacosPlatformDriver {
    fn read_text(&self) -> Result<Option<String>, PalError> {
        let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
        let ns_string_opt = unsafe { pasteboard.stringForType(NSPasteboardTypeString) };
        Ok(ns_string_opt.map(|s| s.to_string()))
    }

    fn write_text(&self, text: &str) -> Result<(), PalError> {
        let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
        unsafe {
            let _ = pasteboard.clearContents();
            let ns_str = NSString::from_str(text);
            if !pasteboard.setString_forType(&ns_str, NSPasteboardTypeString) {
                return Err(PalError::ClipboardError("写入 macOS 剪贴板文本失败".into()));
            }
        }
        Ok(())
    }

    fn read_image(&self) -> Result<Option<Vec<u8>>, PalError> {
        let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
        let ns_data_opt = unsafe { pasteboard.dataForType(NSPasteboardTypePNG) };
        Ok(ns_data_opt.map(|data| data.as_bytes().to_vec()))
    }

    fn write_image(&self, data: &[u8]) -> Result<(), PalError> {
        let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
        unsafe {
            let _ = pasteboard.clearContents();
            let ns_data = NSData::with_bytes(data);
            if !pasteboard.setData_forType(Some(&ns_data), NSPasteboardTypePNG) {
                return Err(PalError::ClipboardError("写入 macOS 剪贴板图片失败".into()));
            }
        }
        Ok(())
    }

    fn send_paste(&self) -> Result<(), PalError> {
        // 1. 预检辅助功能权限，未授权时触发 Accessibility Fallback
        if !Self::is_accessibility_trusted() {
            return Err(PalError::InputSimulationError(
                "未获得 macOS 辅助功能 (Accessibility) 权限，无法模拟 Cmd+V 按键".into(),
            ));
        }

        // 2. 使用 CoreGraphics 注入 Cmd+V 组合按键
        unsafe {
            let key_down = CGEventCreateKeyboardEvent(std::ptr::null_mut(), KEY_CODE_V, true);
            if key_down.is_null() {
                return Err(PalError::InputSimulationError("创建 Cmd+V 按下事件失败".into()));
            }
            CGEventSetFlags(key_down, CG_EVENT_FLAG_COMMAND);
            CGEventPost(CG_HID_EVENT_TAP, key_down);
            CFRelease(key_down);

            thread::sleep(Duration::from_millis(15));

            let key_up = CGEventCreateKeyboardEvent(std::ptr::null_mut(), KEY_CODE_V, false);
            if key_up.is_null() {
                return Err(PalError::InputSimulationError("创建 Cmd+V 释放事件失败".into()));
            }
            CGEventSetFlags(key_up, CG_EVENT_FLAG_COMMAND);
            CGEventPost(CG_HID_EVENT_TAP, key_up);
            CFRelease(key_up);
        }

        Ok(())
    }

    fn start_monitor(&self, callback: Arc<dyn Fn() + Send + Sync>) -> Result<(), PalError> {
        // 1. 防止重复启动监听循环
        if self.is_monitoring.swap(true, Ordering::SeqCst) {
            return Ok(());
        }

        let is_monitoring = self.is_monitoring.clone();
        let interval = self.heartbeat_interval;

        // 2. 启动 250ms 自适应心跳轮询线程 (Heartbeat Poller)
        thread::spawn(move || {
            let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
            let mut last_change_count = unsafe { pasteboard.changeCount() };

            while is_monitoring.load(Ordering::Relaxed) {
                thread::sleep(interval);

                let current_change_count = unsafe { pasteboard.changeCount() };
                if current_change_count != last_change_count {
                    last_change_count = current_change_count;
                    callback();
                }
            }
        });

        Ok(())
    }

    fn is_clipboard_ignored(&self) -> Result<bool, PalError> {
        let pasteboard = unsafe { NSPasteboard::generalPasteboard() };
        let types_opt: Option<Retained<NSArray<_>>> = unsafe { pasteboard.types() };

        if let Some(types) = types_opt {
            let type_names: Vec<String> = types.iter().map(|t| t.to_string()).collect();
            return Ok(Self::matches_ignored_type(&type_names));
        }

        Ok(false)
    }

    fn get_clipboard_source_process(&self) -> Result<Option<String>, PalError> {
        let workspace = unsafe { NSWorkspace::sharedWorkspace() };
        let app_opt: Option<Retained<NSRunningApplication>> =
            unsafe { workspace.frontmostApplication() };

        if let Some(app) = app_opt {
            if let Some(name) = unsafe { app.localizedName() } {
                return Ok(Some(name.to_string()));
            }
            if let Some(bundle_id) = unsafe { app.bundleIdentifier() } {
                return Ok(Some(bundle_id.to_string()));
            }
        }

        Ok(None)
    }

    fn ocr_image(&self, _data: &[u8]) -> Result<String, PalError> {
        // 预留给工单 #31 对接 Apple Vision 原生离线 OCR
        Ok(String::new())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_matches_ignored_type_all_branches() {
        assert!(MacosPlatformDriver::matches_ignored_type(&[
            "org.nspasteboard.TransientType".to_string()
        ]));
        assert!(MacosPlatformDriver::matches_ignored_type(&[
            "org.nspasteboard.ConcealedType".to_string()
        ]));
        assert!(MacosPlatformDriver::matches_ignored_type(&[
            "org.nspasteboard.AutoGeneratedType".to_string()
        ]));
        assert!(MacosPlatformDriver::matches_ignored_type(&[
            "com.agilebits.onepassword".to_string()
        ]));
        assert!(!MacosPlatformDriver::matches_ignored_type(&[
            "public.utf8-plain-text".to_string(),
            "public.png".to_string(),
        ]));
    }

    #[test]
    fn test_default_heartbeat_interval() {
        let driver = MacosPlatformDriver::new();
        assert_eq!(driver.heartbeat_interval, Duration::from_millis(250));

        let driver_custom = MacosPlatformDriver::with_heartbeat_interval(Duration::from_millis(100));
        assert_eq!(driver_custom.heartbeat_interval, Duration::from_millis(100));
    }
}
